#!/bin/sh

# https://www.ibm.com/products/open-enterprise-python-zos/pricing
# click on "Try Free Edition"

if [[ "$ENVIRONMENT_IS_CLEAN" != "YES" ]]; then
    keep="HOME=$HOME LOGNAME=$LOGNAME USER=$USER"
    keep="$keep _BPXK_AUTOCVT=ON ENVIRONMENT_IS_CLEAN=YES PATH=$PATH"
    exec /bin/env -i $keep "$0" "$@"
fi

# === edit these lines ===
PYZ=$HOME/pyz
PYZ_DATE=2020-06-12
PYZ_DATE=2020-07-24
PYZ_PAX=$HOME/HAMB380-$PYZ_DATE.runnable.pax.Z

OLD_ROCKET_PORTED_TOOLS=/rsusr/ported.old
ROCKET_PORTED_TOOLS=/rsusr/ported
# we need to use the "make" that was compiled in ebcdic mode,
# otherwise we get errors like this ".deps/jmemnobs.Plo:1: *** missing separator.  Stop."
# to fix this we will have to insert lines like "@am__fastdepCC_TRUE@	$(AM_V_at)chtag -t -c 1047 $(DEPDIR)/$*.Plo"
# in all the files "Makefile.in"
export ROCKET_PORTED_TOOLS_MAKE=$OLD_ROCKET_PORTED_TOOLS/bin/make

clean='yes'
# === end of lines to edit ===

log=install-$PYZ_DATE.log
touch $log
chtag -t -c 819 $log
exec > $log 2>&1
set -x

mkdir -p $PYZ
cd $PYZ

export PATH=/bin
export LIBPATH=/usr/lib
export PYZ_DIR=usr/lpp/IBM/cyp/v3r8/pyz
export PYZ_PREFIX=$PYZ/$PYZ_DIR
export PATH=$PYZ_PREFIX/bin:$PATH
export LIBPATH=$PYZ_PREFIX/lib:$LIBPATH
export _BPXK_AUTOCVT=ON

if [[ "$clean" == "yes" && -d usr ]]; then
    rm -rf usr
fi
if [[ ! -d usr ]]; then
    pax -z -r -f $PYZ_PAX
    find . > pyz-$PYZ_DATE.list
fi

export CC=/bin/xlclang
export CXX=/bin/xlclang++
# -W'c,DLL' is not needed with xlclang (or with xlc -q64)
CFLAGS=`python3 -c 'import sysconfig; print(sysconfig.get_config_var("CFLAGS"))'  | sed -e "s/-W'c,DLL' //"`
export CFLAGS
CFLAGSFORSHARED=`python3 -c 'import sysconfig; print(sysconfig.get_config_var("CFLAGSFORSHARED"))'`
export CFLAGSFORSHARED
LDSHARED=`python3 -c 'import sysconfig; print(sysconfig.get_config_var("LDSHARED"))'`
export LDSHARED

pip3 install --verbose certifi
export SSL_CERT_FILE=$PYZ_PREFIX/lib/python3.8/site-packages/certifi/cacert.pem

# I can't get /bin/patch to work, so let's use sed

if [[ 1 == 1 ]]; then
    # https://developer.ibm.com/node/2017/04/09/working-with-modules-and-the-node-js-technical-preview-for-zos/
    export _C89_CCMODE=1
    export _CC_CCMODE=1
    export _CXX_CCMODE=1
else
    unset _C89_CCMODE
    unset _CC_CCMODE
    unset _CXX_CCMODE
    # fix: FSUM3010 Specify a file with the correct suffix (.C, .hh, .i, .c, .i, .s, .o, .x, .p, .I, or .a), or a corresponding data set name, instead of -obuild/lib.os390-27.00-8561-3.8/zmq/libzmq.so.
    f=$PYZ_DIR/lib/python3.8/distutils/unixccompiler.py
    if [[ ! -f $f.save ]]; then
        cp $f $f.save
    fi
    sed \
        -e '/ld_args = (objects + self.objects +/{' \
        -e 'N' \
        -e 'c\
\            ld_args = ([opt for opt in lib_opts if opt.startswith("-L")] +\
\                       ["-o", output_filename] + objects + self.objects +\
\                       [opt for opt in lib_opts if not opt.startswith("-L")])' \
        -e '}' \
        -e '/ld_args.extend(\["-Wl,dll", new_pythonx\])/{' \
        -e 'N' \
        -e 'c\
\                    ld_args.append(new_pythonx)\
\                    ld_args[0:0] = ["-Wl,dll", "-q64"]' \
        -e '}' \
        $f.save > $f
fi

rm *.gz
. ./build_pkg-config
. ./build_libzmq
. ./build_zlib
. ./build_jpeg
export PIP_IGNORE_INSTALLED=0
pip3 install --verbose wheel
export PREFIX=$PYZ_PREFIX
. ./build_pyzmq
# bokeh needs Pillow which needs zlib and jpeg

# notebook 6.1 requires argon2-cffi, which we can't build
pip3 install notebook==6.0.3 bokeh cffi==1.14.0 numpy==1.18.2 cryptography==2.8
